# Generated by Django 3.0.2 on 2020-01-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nu_chart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableData',
        ),
    ]
